/**
 * Export conversation to formatted text/markdown file
 */

export function exportConversationToMarkdown(conversation) {
  if (!conversation) return;

  const lines = [];

  // Header
  lines.push('# LLM Council - Decision Report');
  lines.push('');
  lines.push(`**Title:** ${conversation.title}`);
  lines.push(`**Date:** ${new Date(conversation.created_at).toLocaleString()}`);
  lines.push(`**Conversation ID:** ${conversation.id}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Messages
  conversation.messages.forEach((msg, index) => {
    if (msg.role === 'user') {
      lines.push(`## User Question ${Math.floor(index / 2) + 1}`);
      lines.push('');
      lines.push(msg.content);
      lines.push('');
    } else if (msg.role === 'assistant') {
      lines.push(`## Council Response ${Math.floor(index / 2) + 1}`);
      lines.push('');

      // Stage 1: Debate
      if (msg.stage1 && msg.stage1.length > 0) {
        lines.push('### 🗣️ Stage 1: Multi-Round Debate');
        lines.push('');

        const rounds = {};
        msg.stage1.forEach((turn) => {
          if (!rounds[turn.round]) {
            rounds[turn.round] = [];
          }
          rounds[turn.round].push(turn);
        });

        Object.keys(rounds)
          .sort()
          .forEach((round) => {
            lines.push(`#### Round ${round}`);
            lines.push('');

            rounds[round].forEach((turn) => {
              lines.push(`**${turn.role_name}** (${turn.model}):`);
              lines.push('');
              lines.push(turn.message);
              lines.push('');
            });
          });
      }

      // Stage 3: Synthesis
      if (msg.stage3) {
        lines.push('### 📊 Stage 3: Final Synthesis');
        lines.push('');
        lines.push(`**Synthesizer:** ${msg.stage3.role_name || 'Juge'} (${msg.stage3.model})`);
        lines.push('');
        lines.push(msg.stage3.response);
        lines.push('');
      }

      lines.push('---');
      lines.push('');
    }
  });

  // Footer
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by LLM Council on ${new Date().toLocaleString()}*`);

  return lines.join('\n');
}

export function downloadConversationReport(conversation, format = 'md') {
  const content = exportConversationToMarkdown(conversation);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `llm-council-report-${conversation.id.substring(0, 8)}.${format}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export to HTML format for better PDF conversion
 */
export function exportConversationToHTML(conversation) {
  if (!conversation) return;

  const html = [];

  html.push('<!DOCTYPE html>');
  html.push('<html lang="en">');
  html.push('<head>');
  html.push('  <meta charset="UTF-8">');
  html.push('  <title>LLM Council Report</title>');
  html.push('  <style>');
  html.push('    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; line-height: 1.6; color: #333; }');
  html.push('    h1 { color: #764ba2; border-bottom: 3px solid #667eea; padding-bottom: 10px; }');
  html.push('    h2 { color: #667eea; margin-top: 40px; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }');
  html.push('    h3 { color: #764ba2; margin-top: 30px; }');
  html.push('    h4 { color: #666; margin-top: 20px; }');
  html.push('    .metadata { background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 20px 0; }');
  html.push('    .metadata p { margin: 5px 0; }');
  html.push('    .agent-message { background: #f9fafb; border-left: 4px solid #4a90e2; padding: 15px; margin: 15px 0; border-radius: 4px; }');
  html.push('    .synthesis { background: #f0fff0; border-left: 4px solid #4caf50; padding: 20px; margin: 20px 0; border-radius: 8px; }');
  html.push('    .role-name { font-weight: 600; color: #4a90e2; }');
  html.push('    .model-name { font-size: 0.9em; color: #666; }');
  html.push('    pre { background: #f5f5f5; padding: 10px; border-radius: 4px; overflow-x: auto; }');
  html.push('    hr { border: none; border-top: 1px solid #e0e0e0; margin: 40px 0; }');
  html.push('    .footer { text-align: center; color: #999; font-size: 0.9em; margin-top: 60px; }');
  html.push('    @media print { body { max-width: 100%; } }');
  html.push('  </style>');
  html.push('</head>');
  html.push('<body>');

  // Header
  html.push('  <h1>LLM Council - Decision Report</h1>');
  html.push('  <div class="metadata">');
  html.push(`    <p><strong>Title:</strong> ${escapeHtml(conversation.title)}</p>`);
  html.push(`    <p><strong>Date:</strong> ${new Date(conversation.created_at).toLocaleString()}</p>`);
  html.push(`    <p><strong>Conversation ID:</strong> ${conversation.id}</p>`);
  html.push('  </div>');

  // Messages
  conversation.messages.forEach((msg, index) => {
    if (msg.role === 'user') {
      html.push(`  <h2>User Question ${Math.floor(index / 2) + 1}</h2>`);
      html.push(`  <p>${escapeHtml(msg.content).replace(/\n/g, '<br>')}</p>`);
    } else if (msg.role === 'assistant') {
      html.push(`  <h2>Council Response ${Math.floor(index / 2) + 1}</h2>`);

      // Stage 1: Debate
      if (msg.stage1 && msg.stage1.length > 0) {
        html.push('  <h3>🗣️ Stage 1: Multi-Round Debate</h3>');

        const rounds = {};
        msg.stage1.forEach((turn) => {
          if (!rounds[turn.round]) {
            rounds[turn.round] = [];
          }
          rounds[turn.round].push(turn);
        });

        Object.keys(rounds)
          .sort()
          .forEach((round) => {
            html.push(`  <h4>Round ${round}</h4>`);

            rounds[round].forEach((turn) => {
              html.push('  <div class="agent-message">');
              html.push(`    <p><span class="role-name">${escapeHtml(turn.role_name)}</span> <span class="model-name">(${escapeHtml(turn.model)})</span></p>`);
              html.push(`    <p>${escapeHtml(turn.message).replace(/\n/g, '<br>')}</p>`);
              html.push('  </div>');
            });
          });
      }

      // Stage 3: Synthesis
      if (msg.stage3) {
        html.push('  <h3>📊 Stage 3: Final Synthesis</h3>');
        html.push('  <div class="synthesis">');
        html.push(`    <p><span class="role-name">${escapeHtml(msg.stage3.role_name || 'Juge')}</span> <span class="model-name">(${escapeHtml(msg.stage3.model)})</span></p>`);
        html.push(`    <div>${escapeHtml(msg.stage3.response).replace(/\n/g, '<br>')}</div>`);
        html.push('  </div>');
      }

      html.push('  <hr>');
    }
  });

  // Footer
  html.push('  <div class="footer">');
  html.push(`    <p>Generated by LLM Council on ${new Date().toLocaleString()}</p>`);
  html.push('  </div>');

  html.push('</body>');
  html.push('</html>');

  return html.join('\n');
}

export function downloadConversationHTML(conversation) {
  const content = exportConversationToHTML(conversation);
  const blob = new Blob([content], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `llm-council-report-${conversation.id.substring(0, 8)}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
